### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nijeesh4all**
corrected a spelling mistake

### CODE REVIEW

**Review by senesh-deshan — APPROVED** [review]
Thank you @nijeesh4all

**Comment by senesh-deshan** [comment]
> corrected a spelling mistake

Sorry for my mistake @nijeesh4all, but  you made a mistake too. It must be _**different**_

**Comment by nijeesh4all** [comment]
@senesh-deshan  Sorry my bad. 😁

**Comment by senesh-deshan** [comment]
It's okay. Mistakes happen.
Thank you and feel free to correct me.

**Pull request merged**
